baseURL: 'https://blog.mwmbl.org/'
languageCode: 'en-us'
title: 'blog.mwmbl'
theme: "mwmbl"

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Blog
                  url: /
                  weight: 1
                - name: Archive
                  url: archives
                  weight: 5
                - name: Contribute
                  url: https://github.com/mwmbl
                  weight: 200
                - name: Discuss
                  url: https://matrix.to/#/#mwmbl:matrix.org
                  weight: 100
                - name: Donate
                  url: https://opencollective.com/mwmbl
                  weight: 1000

params:
    description: "The people's web search engine"
    disableThemeToggle: true
    ShowBreadCrumbs: true
    defaultTheme: light
    hideFooter: true
    disableScrollToTop: true
    ShowShareButtons: true
    label:
        text: "mwmbl"
        icon: icon.png
        iconHeight: 32